sudo: true
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - '10'

branches:
  only:
    - /.*/

install:
  - pip install --user awscli
  - yarn install --production=false

before_script:
  - yarn bootstrap
  - yarn link

script:
  - yarn build
  - yarn lint
  - yarn build-example
  - yarn test
  #  - yarn doc
  - 'if [ "$TRAVIS_BRANCH" != "develop" ]; then bash scripts/deploy.sh; fi'

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      repo: capsulajs/capsulahub-extensions
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      repo: capsulajs/capsulahub-extensions
      branch: master

after_deploy:
  - git status

notifications:
  email:
    on_failure: always
