sudo: true
language: node_js
node_js:
  - "10"

branches:
  only:
    - /.*/

install:
  - yarn install --production=false

before_script:
  - yarn bootstrap
  - yarn link

script:
  - yarn lint
  - yarn test
  - yarn build

notifications:
  email:
    on_failure: always
